name: CD - Deploy to HuggingFace

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python train.py

      - name: Evaluate model
        run: python evaluate.py

      - name: Install HuggingFace Hub
        run: pip install -U huggingface_hub

      - name: Deploy to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<EOF
          from huggingface_hub import HfApi
          import os
          
          token = os.environ["HF_TOKEN"]
          api = HfApi(token=token)
          repo_id = "cristihanMesa0626/Drug-Classification"
          
          # Subir App
          api.upload_folder(
              folder_path="./App",
              repo_id=repo_id,
              repo_type="space",
              commit_message="Sync App files"
          )
          print("✅ App subida correctamente")
          
          # Subir Model
          api.upload_folder(
              folder_path="./Model",
              path_in_repo="Model",
              repo_id=repo_id,
              repo_type="space",
              commit_message="Sync Model"
          )
          print("✅ Model subido correctamente")
          
          # Subir Results
          api.upload_folder(
              folder_path="./Results",
              path_in_repo="Metrics",
              repo_id=repo_id,
              repo_type="space",
              commit_message="Sync Results"
          )
          print("✅ Results subidos correctamente")
          print("🎉 Deploy completado!")
          EOF