- name: Deploy to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          hf auth login --token $HF_TOKEN
          hf upload cristihanMesa0626/Drug-Classification ./App --repo-type=space --commit-message="Sync App files"
          hf upload cristihanMesa0626/Drug-Classification ./Model /Model --repo-type=space --commit-message="Sync Model"
          hf upload cristihanMesa0626/Drug-Classification ./Results /Metrics --repo-type=space --commit-message="Sync Results"